CREATE TABLE IF NOT EXISTS users (
	id TEXT PRIMARY KEY UNIQUE NOT NULL,
	first_name TEXT NOT NULL,
	last_name TEXT NOT NULL,
	email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	role TEXT NOT NULL
);
